#!/bin/bash

# automatically change configuration of Mac OS X based on location
# author: Rocco Georgi <rocco@pavingways.com>
# version: 0.4.0

# original author: Onne Gorter <o.gorter@gmail.com>
# url: http://tech.inhelsinki.nl/locationchanger/
# version: 0.4

# redirect all IO to a logfile
#mkdir -p /usr/local/var/log
#exec &>/usr/local/var/log/locationchanger.log
# redirect all IO to /dev/null (comment this in if you don#t want to write to logfile)
exec 1>/dev/null 2>/dev/null

# get a little breather before we get data for things to settle down
sleep 2


# get SSID
SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | awk '/ SSID:/ {print $2}'`
echo `date` "New SSID found: $SSID"

# empty location var
LOCATION=

# LOCATIONS
# (use to be used Location name here)
# =============================================
Location_Internal="Interno"
Location_External="Externo"

# SSIDS
# =====
SSID_VPN=1153rwfgtwcp08

# SSID -> LOCATION mapping
case $SSID in
	$SSID_VPN ) LOCATION="$Location_Internal";;
  * ) LOCATION="$Location_External"
esac
	REASON="SSID changed to $SSID"


# still didn't get a location -> use Location_Automatic
if [ -z "$LOCATION" ]; then
	LOCATION="$Location_External"
	REASON="Automatic Fallback"
fi

# change network location
scselect "$LOCATION"

case $LOCATION in
	$Location_External )
		osascript -e 'display notification "Network Location Changed to Externo" with title "Network Location Changed"'
	;;

	$Location_Internal )
		osascript -e 'display notification "Network Location Changed to Interno" with title "Network Location Changed"'
	;;
esac

echo "--> Location Changer: $LOCATION - $REASON"

exit 0
